### ISSUE TITLE
Participants-Contributors-Conveners (Card)

### ISSUE THREAD

**Issue by parkerdavis1** [parkerdavis1/CCAM#18]
We discussed displaying contributors as a sort of card, possibly including:
- name
- image
- list of research interests
- external link

Conveners and participants need to be distinguished somehow:
- cards placed under conveners and participants headings
- other options(?)

These would be displayed on the Projects Page if I'm not mistaken. @garrett-laroy-johnson, would they also appear on programs?

@garrett-laroy-johnson  Terminology clarification: there are two categories, right? 
- Participants/contributors & conveners

**Comment by parkerdavis1** [comment]
@garrett-laroy-johnson  so I started putting some participants in the tagiverse. 
See: https://ccam-staging.netlify.app/programs/23-5-dispersionology/

As I understand it, the goal is to display the participants/conveners somehow on projects/programs that link to a ‘tags’ page with all their associated data. 

But here is an interesting problem: The original post has participants listed with their instruments, useful information. Programmatically displaying participants in this way automates some things which is nice, but prevents flexibility. 

Food for thought for clarifying what your needs are. 

![Screen Shot 2024-01-20 at 05 24 13](https://github.com/parkerdavis1/CCAM/assets/92223355/5c4d137f-2253-4dc8-b14e-be65eb8d67ad)

**Comment by parkerdavis1** [comment]
you'll have to excuse me for blasting the issues...

Will it be desirable to show the same card, same information, same photo, same auxillary info, for every time Garrett Laroy Johnson is listed as participant/convener across the site? All programs, projects, etc. Or will each event and project have slightly different needs (such as the fact that they played glockenspiel for this particular mallet-fest at DAR // facilitated hypnogogic painting at the local drum circle (these are the types of events you do right?))? 

Instead of predefining and standardizing across all realms for all time, I'm thinking maybe some of these things would be better left done manually. And maybe, a generalized tag system might accomplish what you need. It depends what you want. Once you have some time to think things over, it might be worthwhile for Gar and I to talk on the phone again so I can interrogate you to find out what you envision and the best way to bring that vision to fruition. Don't worry about how one might implement things in the code, just think about what exactly you might want, big picture, then I can push and pull, thinking about how best to pull it off. Then once we nail that down, Ioan can work his design magic to tie it all together. Lmk

**Comment by ioanbutiu** [comment]
@parkerdavis1 @garrett-laroy-johnson sounds like there are some site architecture decisions to be made but here's a pass at an expanded project page: https://www.figma.com/file/NkOPmhCvYwwuBzdrXYHJCp/CCAM?type=design&node-id=498-4155&mode=design&t=iSeaWj8p72PEILsS-4

**Comment by parkerdavis1** [comment]
Cool, project page looks good to me. Big picture/fine details still need to be pinned down.  I’ll wait to hear from @garrett-laroy-johnson before I start working on it.

**Comment by garrett-laroy-johnson** [comment]
@ioanbutiu the design looks fab. 

OK, so the question about roles for projects. This is another thing that is gonna kinda vary based on the project. Just now I thought about a new project we are brewing up that will have "microresidents". 

So, I wonder if there is... another way. something where the people cards are dynamically broken up into categories. Maybe with some kind of headers? @ioanbutiu ?



```
people: 
   - label: conveners
     list: 
       - joe camel
   - label: participants
      list:  
       - child smokesalot
       - cigs aplenty jr
       - Nico Teen
```

but is flexible to accept other categories 

```
people:
   - label: principle investigator
     list:
         - Cowboy Killer
   - label: microresidents
     list: 
        - Cool Aid Man
        - Sprague the Whisperer
   - label: The Brothers Cage
     list: 
        - Nick Cage
        - Johnny Cage
```

Thoughts for this humble entreaty, @parkerdavis1 ??

**Comment by garrett-laroy-johnson** [comment]
To comment on the instrument elaboration for instance, maybe we have to treat that as a special case and we would include some kind of program in the markdown.

**Comment by parkerdavis1** [comment]
@garrett-laroy-johnson are these people cards going on both programs and projects? Or just projects? 

"To comment on the instrument elaboration for instance, maybe we have to treat that as a special case and we would include **some kind of program** in the markdown."

Huh?

I'll take swing at how I think this would be best be solved (with flexibility in mind)

**Comment by garrett-laroy-johnson** [comment]
“Program” here means like an image of a concert program. Sorry! I didn’t
think about the possible confusion :)

**Comment by parkerdavis1** [comment]
@garrett-laroy-johnson are these people cards going on both programs and projects? Or just projects?

**Comment by parkerdavis1** [comment]
Person cards are in projects - SEE 👀
https://ccam-staging.netlify.app/projects/future-rhythm-machines/

People with cards must have a yaml data file in `src/content/people/*`

The name of the yaml file is the key to their data, so you list the key in the list without .yaml:
```
people:
    - label: Principle Investigator
      list:
          - garrett-laroy-johnson
    - label: Conveners
      list:
          - fake-person
          - garrett-laroy-johnson
```

![Screenshot 2024-01-29 at 11 51 25 AM](https://github.com/parkerdavis1/CCAM/assets/92223355/061adf5d-190c-48ea-9676-a579e15e1f75)

I find dealing with yaml nested arrays/objects finicky and annoying, but hey, it works! I don't have an immediate better suggestion.

Play with it @garrett-laroy-johnson, let me know what you think
